---
title: "Complex Measurement Models - MTMM Test for Construct Validity - CTUM"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Part 2: MTMM(Multitrait-multimethod models) Models

## Freely Correlated Traits/Uncorrelated Methods (CTUM)

```{r}
mtmm_data <- read.table("ind7mt.dat")
```

```{r}
colnames(mtmm_data) <- c(
  'scself',
  'sctch',
  'scpar',
  'scpeer',
  'acself',
  'actch',
  'acpar',
  'acpeer',
  'ecself',
  'ectch',
  'ecpar',
  'ecpeer',
  'mcself',
  'mctch',
  'mcpar',
  'mcpeer'
)
```

## Model Specification

```{r}
mtmm_ctum <- '
# Latent factors
# F1-F4 are latent methods (parent, teacher, self, peer report)
F1 =~ NA*scself + sctch + scpar + scpeer
F2 =~ NA*acself + actch + acpar + acpeer
F3 =~ NA*ecself + ectch + ecpar + ecpeer
F4 =~ NA*mcself + mctch + mcpar + mcpeer

# F5-F8 are latent traits (social, academic, english, math competence)
F5 =~ NA*scself + acself + ecself + mcself
F6 =~ NA*sctch + actch + ectch + mctch 
F7 =~ NA*scpar + acpar + ecpar + mcpar
F8 =~ NA*scpeer + acpeer + ecpeer + mcpeer

# Latent variable variances fixed to 1
F1 ~~ 1*F1
F2 ~~ 1*F2
F3 ~~ 1*F3
F4 ~~ 1*F4
F5 ~~ 1*F5
F6 ~~ 1*F6
F7 ~~ 1*F7
F8 ~~ 1*F8

# Covariances between latent methods and latent traits fixed to 0
# (i.e., methods are uncorrelated with traits)
F1 ~~ 0*F5
F1 ~~ 0*F6
F1 ~~ 0*F7
F1 ~~ 0*F8
F2 ~~ 0*F5
F2 ~~ 0*F6
F2 ~~ 0*F7
F2 ~~ 0*F8
F3 ~~ 0*F5
F3 ~~ 0*F6
F3 ~~ 0*F7
F3 ~~ 0*F8
F4 ~~ 0*F5
F4 ~~ 0*F6
F4 ~~ 0*F7
F4 ~~ 0*F8

# Covariances among methods fixed to zero 
# (i.e., methods are uncorrelated)

F5 ~~ 0*F6
F5 ~~ 0*F7
F5 ~~ 0*F8
F6 ~~ 0*F7
F6 ~~ 0*F8
F7 ~~ 0*F8

# Covariances among traits left out of the syntax
# (i.e., traits are free to covary)

# Variance of ACSELF fixed to 0
acself ~~ 0*acself
'
```

## Fitting the model

```{r}

mtmm_ctum_fit <- cfa(model = mtmm_ctum,
               data = mtmm_data,
               missing = "ml",
               estimator = "mlr",
               control = list(iter.max = 1000)
               )

```

Note that fit is improving!

## Model Output 

### Model summary

```{r}
summary(mtmm_ctum_fit, 
        standardized = TRUE, 
        rsquare = TRUE,
        fit.measures = TRUE)
```
